elementName: rvn-settings-user

viewDataSchema:
  type: object
  properties: {}

refs:
  fileexplorer:
    eventListeners:
      data-changed:
        handler: handleDataChanged

template: 
  - rtgl-view d=h w=f h=f: 
    - rtgl-view w=f h=f p=md w=240:
      - rvn-resource-types .resourceCategory=resourceCategory .selectedResourceId=selectedResourceId:
      - rvn-file-explorer#fileexplorer .items=flatItems .repositoryTarget=repositoryTarget:
    - rtgl-view w=f h=f p=lg:
      - rtgl-text s=h2: User Settings
      - rtgl-view g=lg mt=lg:
        - rtgl-text s=md: User settings content will go here
        - rtgl-text s=sm c=mu-fg: This is a placeholder for the user settings interface
    - rvn-detail-panel .title=detailTitle .fields=detailFields .emptyMessage=detailEmptyMessage: